### PR TITLE
new converter for keepass exported csv files

### PR DESCRIPTION
**Pull request by nean-and-i**
adoped by nean for keepasXC CSV exports

1.) KeepassXC export as CSV
2.) copy Keepassxc.pm into Converters folder
3.) perl convert_to_1p4.pl keepassxc nean.csv -v
NOTE: groupname to tag conversation -> tags based on groupfolder will be be assigned every record

### CODE REVIEW

**Comment by mikecappella** [comment]
Thanks nean,

I have the converter module from your Dropbox, that you gave to lars.  I'll take a look at KeepassXC and its output.  Once I test the output, verify the converter, and update the docs, I'll include it in my releases.  Typically I wait for someone who has a vested interest in testing a converter, so I can work with them to resolve issues.

**Comment by nean-and-i** [comment]
all clear, thanks for the feedback.

please note, my conversion module works for both "keepassx" and "keepasxc", but the name "Keepassxc" can lead to misconceptions. I'll leave it up to you to decide whetever its name should be.

Please note, that at least on my end, the existing keepassx converter is just not working.

```
$ perl convert_to_1p4.pl keepassx test.csv -v
Uncaught exception from user code:

    not well-formed (invalid token) at line 1, column 7, byte 7:
    "Group","Title","Username","Password","URL","Notes"
    ======^
    "Root","KeePassHttp Settings","","","",""
    "Root/sites","XXXXXXXXXXX,"XXXXXXXXX","XXXXXXXX","XXXXXXXX",""
     at /opt/local/lib/perl5/site_perl/5.24/darwin-thread-multi-2level/XML/Parser.pm line 187.
    XML::Parser::parse(XML::Parser=HASH(0x7fb9632e26c8), "\"Group\",\"Title\",\"Username\",\"Password\",\"URL\",\"Notes\"\x{a}\"Root\",\"K"...) called at /opt/local/lib/perl5/site_perl/5.24/XML/XPath/XMLParser.pm line 74
    XML::XPath::XMLParser::parse(XML::XPath::XMLParser=HASH(0x7fb9636066b0)) called at /opt/local/lib/perl5/site_perl/5.24/XML/XPath.pm line 154
    XML::XPath::find(XML::XPath=HASH(0x7fb9637b2868), "//group") called at Converters/Keepassx.pm line 62
    Converters::Keepassx::do_import("test.csv", undef) called at convert_to_1p4.pl line 125
```



I've sucessfully tested my module (keepasxc) with following keepassX(c) versions

keepassx 2.0.3 -> csv export-> OK
```
 $ perl convert_to_1p4.pl keepassxc test.csv -v
Imported 186 items
Exported 180 login items
Exported 6 note items
Exported 186 total items
You may now import the file 1P_import.1pif into 1Password
```

keepassxc 2.2.0 -> csv export -> OK
```
$ perl convert_to_1p4.pl keepassxc test.csv -v
Imported 186 items
Exported 180 login items
Exported 6 note items
Exported 186 total items
You may now import the file 1P_import.1pif into 1Password
```

Also I tried to convert keepass2 csv1.x export files, but it is not yet working, but can be fixed as well.

keepass 2.36 (via wine) -> csv 1.x export -> FAIL

```
$ perl convert_to_1p4.pl keepassxc test.csv -d
CSV column names do not match expected names
```



thanks,
nean

**Comment by mikecappella** [comment]
Let's have this conversation over here:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility#latest

Agilebit's Github repository is not the right place for this, but I would like to continue discussion w/you.

The keepassx converter only supports KeepassX 1.03 (not 2.0) - 2.0 does not export XML, but CSV.  From the README.pdf file:

Note: KeePassX version 2.0 does not support an XML export. However, its database can be read by KeePass 2. If you can install Keepass 2, you can use the Keepass 2 instructions above to perform the export and conversion using the keepass2 converter. Unfortunately Keepass 2 installation on an OS X system is non-trivial, so if you happen to have a PC, do the export there. KeePassX version 2 can export to CSV, so you may also use the csv converter to perform the conversion.

**Comment by robyoder** [comment]
@mikecappella are you incorporating these changes into your code which you will submit as a PR? Or is this a candidate to be merged?

**Comment by mikecappella** [comment]
A modified version of the changes has already been included in my code.

I use email because I need the quick, informal back-and-forth conversation with the user who is engaged and able to quickly test things for me.  Sometimes I need to get samples, or other info, not relevant or necessary for public consumption.

The OP and I resolved the the change requests, and we included some new enhancements.  This is now done, and you'll get the final result.

**Pull request closed without merging**
